on:
  push:
    branches:
      - master

name: ğŸš€ Deploy Laravel Website on Push

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get Latest Code
        uses: actions/checkout@v3

      - name: âš™ï¸ Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # - name: ğŸ“¦ Install Composer Dependencies
      #   run: composer install --no-ansi --no-interaction --no-progress --no-scripts --no-suggest --optimize-autoloader
      
      - name: ğŸ§ª Run Unit Tests
        run: vendor/bin/phpunit --testsuite=Unit

      - name: ğŸ§ª Run Feature Tests
        run: vendor/bin/phpunit --testsuite=Feature

      - name: ğŸ“‚ Sync Files to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: ${{ secrets.FTP_PORT }}